# 设备模式
READER_MODE = 0
ENROLLER_MODE = 1
DEVICE_MODE = READER_MODE # Check Here

# HTTP服务
API_BASE_URL = "http://10.144.85.43:8080/api"
REQUEST_TIMEOUT = 5
CARD_READ_TIMEOUT = 1

# 硬件配置
MOTOR_DURATION_SECONDS = 0.5